

    <html>
    <head>
        <title>NYP/CUMC - Report for Multiple Sclerosis, generated by the Tatonetti Lab</title>
        <link rel="stylesheet" type="text/css" href="dxreport.css">
        <link rel="stylesheet" type="text/css" href="print_dxreport.css" media="print">
        
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <!--Adding the d3 javaascript-->
        <script type="text/javascript" src="d3.min.js"></script>
        
        <style>
            
            #tooltip {
            position: absolute;
            width: 40px;
            height: 20px;
            padding: 10px; 
            background-color: white;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            -webkit-box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.4);
            -moz-box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.4);
            box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.4);
            pointer-events: none;
            }

            #tooltip.hidden {
            display: none;
            }

            #tooltip p {
            margin: 0;
            font-family: sans-serif;
            font-size: 30px;
            line-height: 20px;
            }     
        </style>


    </head>
    <body>
        <div id="page">
            <div id="logo">
                <img src="images/cumc_logo.png"/>
            </div>
            <div id="header">
                <h1>Multiple Sclerosis</h1>
                <h3>4,287 total in-patients at NYP/CUMC</h3>
                <p>1,155 males, 3,129 females, and 0 unknown</p>
            </div>
            
            <div class="section">
                <h2>Number of patients broken down by length of observation at CUMC</h2>
                <p>
                    The <i>observation period</i> for a given patient is the length of time where the
                    patient has data. If a patient visits NYP only once then this value will be 0 (aka &le; 1 year). 
                    If the patient visits multiple times over the course of five years then this value 
                    will be 5. The plot on the left is the distribution of observation periods, the plot
                    on the right is the cumulative number of patients with <i>at least</i> a certain
                    number of years of observations. For example, there are 463 males
                    and 1,383 females with at least a 5 year observation period.
                </p>
                <div id="visuals">
                    <!-- I) YEAR OF DIAGNOSIS FOR MULTIPLE SCLEROSIS -->      
                    <div id="tooltip" class="hidden">
                        <p><strong></strong></p>
                        <p><span id="value">20</span></p>
                    </div>

                    <script type="text/javascript"> 
                        var pL = [
                            <?php
                                $dXList = array();
                                ini_set('auto_detect_line_endings',TRUE);
                                $handle = fopen('msReportData_DXbyYear.txt','r') or die("Unable to open file!"); 
                                if($handle){
                                    while ( ($data = fgetcsv($handle, 1000) ) !== FALSE ) {
                                        $x = explode(chr(9), $data[0]);
                                        $Year = $x[0];
                                        $NumDiagnoses = $x[1];

                                        $dXYear = array(
                                            $Year,
                                            $NumDiagnoses
                                        );

                                        array_push($dXList, $dXYear);
                                    }
                                } else {
                                    echo "Error reading File";
                                }
                                fclose($handle);
                                echo json_encode($dXList);
                            ?>
                        ];

                        //Define Variables
                        var buffer = 40;
                        var barWidth = 45; // modifier
                        var barBuffer = 5;
                        var labelBuffer = 5;
                        var w = (barWidth+barBuffer)*pL[0].length; // Width to include every entry
                        var h = 550; 

                        //Defining maxHeight - vertical limit of the graph
                        var maxHeight = d3.max(pL[0], function(d) {
                            return parseInt(d[1]); // Number of patients
                        });
                        var maxYear = d3.max(pL[0], function(d) {
                            return parseInt(d[0]);
                        });
                        var minYear = d3.min(pL[0], function(d) {
                            return parseInt(d[0]);
                        });

                        var yScale = d3.scale.linear()
                            .domain([0, maxHeight])
                            .range([0, h-buffer]);

                        var yAxisScale = d3.scale.linear()
                            .domain([0, maxHeight])
                            .range([h-buffer, 0]);

                        var xScale = d3.scale.linear()
                            .domain([minYear, maxYear])
                            .range([buffer, w]);
                        
                        var xAxisScale = d3.scale.linear()
                            .domain([0, pL[0].length])
                            .range([buffer, w]);

                        var svg = d3.select("#visuals")
                            .append("svg")
                            .attr({
                                width: w,
                                height: h,
                            });

                        //Function to make Bars
                        var makeBars = function() {
                            svg.selectAll("rect")
                            .data(pL[0])
                            .enter()
                            .append("rect")
                            .attr({
                                width: barWidth, 
                                height: function(d) {
                                    if(!isNaN(parseInt(d[1]))) {return (yScale(parseInt(d[1])))}
                                },
                                fill: function(d){
                                    return "rgb(10, 100, 100)";
                                },
                                y: function(d){ if(!isNaN(parseInt(d[1]))) {return h-buffer-(yScale(parseInt(d[1])))}},
                                x: function(d){ if(!isNaN(parseInt(d[0]))) {
                                    return xScale(parseInt(d[0]))}},
                            })
                            //Adding the mouseOver function - Hover to highlight
                            .on("mouseover", function(d) {
                                var xPosition = parseFloat(d3.select(this).attr("x"));
                                var yPosition = parseFloat(d3.select(this).attr("y"))-100; // Correcting Value

                                d3.select("#tooltip")
                                .style("left", xPosition + "px")
                                .style("top", yPosition+70 + "px")
                                .select("#value")
                                .text(d[1]); //function(d) {return d[0]}),

                                d3.select("#tooltip").classed("hidden", false);
                            })
                            .on("mouseout", function() {
                                d3.select("#tooltip").classed("hidden", true);
                            })
                        }

                        //Function to makeLabels
                        var makeLabels = function() {
                            svg.selectAll("text")
                            .data(pL[0])
                            .enter()
                            .append("text")
                            .text(function(d) {return d[0]})
                            .attr({
                                y: function(d){ if(!isNaN(parseInt(d[1]))) {return h-75}}, 
                                x: function(d){ if(!isNaN(parseInt(d[0]))) {return xScale(parseInt(d[0]))}},
                                "font-size": 20,
                                "font-family": "sans-serif",
                                fill: "black" 
                            })
                        }
                        makeBars();
                        makeLabels();

                        //Interesting Note - this needs to go after making the bars/labels or else the labels will not appear
                        var yAxis = d3.svg.axis()
                            .scale(yAxisScale)
                            .orient("left")
                            .ticks(13);
                        
                        var xAxis = d3.svg.axis()
                            .scale(xAxisScale)
                            .orient("bottom")

                        svg.append("g")
                            .attr("class", "axis")
                            .attr("transform", "translate(" + (buffer-10) + ",0)")
                            .call(yAxis);
                        
                        svg.append("g")
                            .attr("class", "axis")
                            .attr("transform", "translate(0," + (h-45) + ")")
                            .call(xAxis);
                    </script>
                </div>
            </div>
            
            <div class="section">
                <h2>Year of First Diagnosis</h2>
                <p>
                    The <i>First Diagnosis</i> is the first record we have of the patient being diagnosed
                    with Multiple Sclerosis. Note that the patient may have been diagnosed at another clinic
                    or hospital before coming to NYP/CUMC. This date is the first diagnosis date at NYP/CUMC. 
                    Note, years with 5 or fewer patients have been removed to preserve privacy.
                    
                </p>
                <div class="figure">
                    
                    
                </div>
            </div>
            
            <div class="section">
                <h2>Age First Diagnosis</h2>
                <p>
                    The age of the patients at the time they were <i>first diagnosed</i> with Multiple Sclerosis 
                    at NYP/CUMC. Note,
                    ages with 5 or fewer patients have been removed to preserve privacy.
                </p>
                <div class="figure">
                    
                    
                    
                </div>
            </div>
            
            <div class="section">
                <h2>Top 10 Prescriptions</h2>
                <p>
                    These are the top 10 prescriptions following the diagnosis of Multiple Sclerosis 
                    and within a certain time inteval. At 
                    this time these are not normalized for the frequency of use for the prescriptions so 
                    many of the top ranked drugs are simply the most commonly used medications.
                </p>
                <div class="figure">
                    
                    
                    
                    
                </div>
            </div>
            
            <div class="section">
                <h2>Top 10 Secondary Diagnoses</h2>
                <p>
                    These are the top 10 secondary diagnoses following the diagnosis of Multiple Sclerosis 
                    and within a certain time interval. At 
                    this time these are not normalized for the frequency so 
                    many of the top ranked conditions are simply the most common.
                </p>
                <div class="figure">
                   
                    
                    
                    
                </div>
            </div>
            
            <div id="footer">
                This report was generated by the <a href="http://tatonettilab.org">Tatonetti Lab</a> 
                at Columbia University Medical Center.
            </div>
        </div>
    </body>
    </html>
    
    